- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: run nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: import tasks from common role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: extract frontend code
  ansible.builtin.unarchive:
    src: /tmp/doctor-appointment.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy config file
  ansible.builtin.template:
    src: doctor.conf.j2
    dest: /etc/nginx/default.d/doctor.conf
  notify:
  - restart nginx

# - name: restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted